version: 2
registries:
  ghcr-io:
    type: docker-registry
    url: https://ghcr.io
    username: lgoette
    password: ${{secrets.GHCR_PAT}}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - "lgoette"
      - "MayNiklas"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/modules/home-assistant"
    registries:
      - ghcr-io
    reviewers:
      - "lgoette"
    schedule:
      interval: "weekly"
