---
kind: pipeline
type: exec
name: Build all hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: Show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata
  - nix --experimental-features "nix-command flakes" flake check

- name: Run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace

- name: Build minecraft
  commands:
  - nix build -v '.#nixosConfigurations.minecraft.config.system.build.toplevel'

trigger:
  branch:
  - main
  event:
  - push
  - pull_request
  
---
kind: pipeline
type: exec
name: Build flake apps

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: Build bukkit-spigot
  commands:
  - nix build .#bukkit-spigot

trigger:
  branch:
  - main
  event:
  - push


---
kind: pipeline
type: exec
name: build flake update

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: create result-old files
  commands:
  - nix build -v '.#nixosConfigurations.minecraft.config.system.build.toplevel'
  - mv result minecraft-old

- name: flake update
  commands:
  - nix --experimental-features "nix-command flakes" flake update
  
- name: Show git diff
  commands:
  - git diff

- name: Show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata
  - nix --experimental-features "nix-command flakes" flake check

- name: Run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace

- name: Build minecraft
  commands:
  - nix build -v '.#nixosConfigurations.minecraft.config.system.build.toplevel'
  - mv result minecraft-new

- name: Print report
  commands:
  - echo "minecraft:" && nix store diff-closures $(readlink -f minecraft-old) $(readlink -f minecraft-new)

trigger:
  branch:
  - main
  event:
  - pull_request
  - cron
