---
# nix run nixpkgs#mustache-go -- drone.json drone-yaml.mustache > .drone.yml
kind: pipeline
type: exec
name: flake info

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata

- name: run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace

---
kind: pipeline
type: exec
name: build amd64 hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: build minecraft
  commands:
  - nix build '.#nixosConfigurations.minecraft.config.system.build.toplevel' --out-link result-minecraft
  - nix path-info --closure-size -h $(readlink -f result-minecraft)

- name: build lamafarm
  commands:
  - nix build '.#nixosConfigurations.lamafarm.config.system.build.toplevel' --out-link result-lamafarm
  - nix path-info --closure-size -h $(readlink -f result-lamafarm)

- name: upload to binary cache via s3
  commands:
  - nix run 'github:mayniklas/nixos'#s3uploader
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  event:
  - cron
  - push

---
kind: pipeline
type: exec
name: build arm64 hosts

platform:
  os: linux
  arch: arm64

clone:
  depth: 1

steps:

- name: build lamabasis
  commands:
  - nix build '.#nixosConfigurations.lamabasis.config.system.build.toplevel' --out-link result-lamabasis
  - nix path-info --closure-size -h $(readlink -f result-lamabasis)

- name: upload to binary cache via s3
  commands:
  - nix run 'github:mayniklas/nixos'#s3uploader
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  event:
  - cron
  - push

---
kind: pipeline
type: exec
name: build amd64 flake apps

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: Build bukkit-spigot
  commands:
  - nix build .#bukkit-spigot --out-link result-bukkit-spigot
  - nix path-info --closure-size -h $(readlink -f result-bukkit-spigot)

- name: upload to binary cache via s3
  commands:
  - nix run 'github:mayniklas/nixos'#s3uploader
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  event:
  - push
  - cron
