# When updating, check releasenotes (https://www.home-assistant.io/blog/categories/core/) for (Strg+F: "Backward-incompatible changes")
FROM ghcr.io/home-assistant/home-assistant:2024.9.3
RUN apk update && apk add samba