FROM ghcr.io/home-assistant/home-assistant:stable
RUN apk update && apk add samba
LABEL org.opencontainers.image.title="home-assistant" \
      org.opencontainers.image.description="home-assistant, extended with samba package for remote management of windows machine"