{
  "labels": {
    "backend": "local",
    "platform": "linux/arm64"
  },
  "steps": [
    {
      "commands": [
        "nix flake show"
      ],
      "image": "bash",
      "name": "Nix flake show"
    },
    {
      "commands": [
        "attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default"
      ],
      "image": "bash",
      "name": "Setup Attic",
      "environment": {
        "ATTIC_KEY": {
          "from_secret": "attic_key"
        }
      }
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.lamabasis.config.system.build.toplevel' -o 'result-lamabasis' -v"
      ],
      "image": "bash",
      "name": "Build lamabasis"
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-lamabasis')"
      ],
      "image": "bash",
      "name": "Show lamabasis info"
    },
    {
      "commands": [
        "attic push lounge-rocks:nix-cache 'result-lamabasis'"
      ],
      "image": "bash",
      "name": "Push lamabasis to Attic"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.lamaoutpost.config.system.build.toplevel' -o 'result-lamaoutpost' -v"
      ],
      "image": "bash",
      "name": "Build lamaoutpost"
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-lamaoutpost')"
      ],
      "image": "bash",
      "name": "Show lamaoutpost info"
    },
    {
      "commands": [
        "attic push lounge-rocks:nix-cache 'result-lamaoutpost'"
      ],
      "image": "bash",
      "name": "Push lamaoutpost to Attic"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.pi4b.config.system.build.toplevel' -o 'result-pi4b' -v"
      ],
      "image": "bash",
      "name": "Build pi4b"
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-pi4b')"
      ],
      "image": "bash",
      "name": "Show pi4b info"
    },
    {
      "commands": [
        "attic push lounge-rocks:nix-cache 'result-pi4b'"
      ],
      "image": "bash",
      "name": "Push pi4b to Attic"
    }
  ],
  "when": [
    {
      "event": "manual"
    },
    {
      "branch": "main",
      "event": "push"
    },
    {
      "branch": "update_flake_lock_action",
      "event": "push"
    }
  ]
}
