{
  "labels": { "backend": "local" },
  "platform": "linux/amd64",
  "steps":
    [
      {
        "commands": ["nix flake show"],
        "image": "bash",
        "name": "Nix flake show",
      },
      {
        "commands": ["nix flake check"],
        "image": "bash",
        "name": "Nix flake check",
      },
      {
        "commands":
          [
            "attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default",
          ],
        "image": "bash",
        "name": "Setup Attic",
        "secrets": ["attic_key"],
      },
      {
        "commands":
          [
            "nix build '.#nixosConfigurations.lamafarm.config.system.build.toplevel' -o 'result-lamafarm'",
          ],
        "image": "bash",
        "name": "Build lamafarm",
      },
      {
        "commands":
          ["nix path-info --closure-size -h $(readlink -f 'result-lamafarm')"],
        "image": "bash",
        "name": "Show lamafarm info",
      },
      {
        "commands": ["attic push lounge-rocks:nix-cache 'result-lamafarm'"],
        "image": "bash",
        "name": "Push lamafarm to Attic",
      },
      {
        "commands":
          [
            "nix build '.#nixosConfigurations.minecraft.config.system.build.toplevel' -o 'result-minecraft'",
          ],
        "image": "bash",
        "name": "Build minecraft",
      },
      {
        "commands":
          ["nix path-info --closure-size -h $(readlink -f 'result-minecraft')"],
        "image": "bash",
        "name": "Show minecraft info",
      },
      {
        "commands": ["attic push lounge-rocks:nix-cache 'result-minecraft'"],
        "image": "bash",
        "name": "Push minecraft to Attic",
      },
    ],
}
