{
  "labels": { "backend": "local" },
  "platform": "linux/arm64",
  "when": { "event": "manual" },
  "steps":
    [
      {
        "commands":
          [
            "crab_share --zip-single-file --expires 7d --purge $(nix build --print-out-paths --no-link '.#pi4b-image')/sd-image/pi4b-image-*-aarch64-linux.img",
          ],
        "image": "bash",
        "name": "upload pi4b image",
        "environment":
          [
            "S3_URL=https://s3.eu-central-003.backblazeb2.com",
            "S3_BUCKET=crab-share",
            "S3_REGION=eu-central-003",
            "S3_ACCESS_KEY=003d560892a1b3a0000000002",
          ],
        "secrets": ["S3_SECRET_KEY"],
      },
    ],
}
