{
  "labels": {
    "backend": "local",
    "platform": "linux/amd64"
  },
  "steps": [
    {
      "commands": [
        "nix flake show"
      ],
      "image": "bash",
      "name": "Nix flake show"
    },
    {
      "commands": [
        "attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default"
      ],
      "image": "bash",
      "name": "Setup Attic",
      "secrets": [
        "attic_key"
      ]
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.lamafarm.config.system.build.toplevel' -o 'result-lamafarm'"
      ],
      "image": "bash",
      "name": "Build lamafarm"
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-lamafarm')"
      ],
      "image": "bash",
      "name": "Show lamafarm info"
    },
    {
      "commands": [
        "attic push lounge-rocks:nix-cache 'result-lamafarm'"
      ],
      "image": "bash",
      "name": "Push lamafarm to Attic"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.lasse-laptop.config.system.build.toplevel' -o 'result-lasse-laptop'"
      ],
      "image": "bash",
      "name": "Build lasse-laptop"
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-lasse-laptop')"
      ],
      "image": "bash",
      "name": "Show lasse-laptop info"
    },
    {
      "commands": [
        "attic push lounge-rocks:nix-cache 'result-lasse-laptop'"
      ],
      "image": "bash",
      "name": "Push lasse-laptop to Attic"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.minecraft.config.system.build.toplevel' -o 'result-minecraft'"
      ],
      "image": "bash",
      "name": "Build minecraft"
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-minecraft')"
      ],
      "image": "bash",
      "name": "Show minecraft info"
    },
    {
      "commands": [
        "attic push lounge-rocks:nix-cache 'result-minecraft'"
      ],
      "image": "bash",
      "name": "Push minecraft to Attic"
    }
  ],
  "when": [
    {
      "event": "manual"
    },
    {
      "branch": "main",
      "event": "push"
    },
    {
      "branch": "update_flake_lock_action",
      "event": "push"
    }
  ]
}
